default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mafia-backend_development

test:
  <<: *default
  database: mafia-backend_test

production:
  <<: *default
  host: <%= ENV['CHARLES_DATABASE_URL'] %>
  database: <%= ENV['CHARLES_DATABASE_NAME'] %>
  username: <%= ENV['CHARLES_DATABASE_USERNAME'] %>
  password: <%= ENV['CHARLES_DATABASE_PASSWORD'] %>

  # database: mafia-backend_production
  # username: mafia-backend
  # password: <%= ENV['TEST-APP_DATABASE_PASSWORD'] %>