default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mafia-backend_development

test:
  <<: *default
  database: mafia-backend_test

production:
  <<: *default
  database: mafia-backend_production
  username: mafia-backend
  password: <%= ENV['TEST-APP_DATABASE_PASSWORD'] %>